#Elasticsearch config file

node.master: true
node.data: true
node.ingest: true
node.ml: true
xpack.ml.enabled: true

cluster.remote.connect: false

cluster.name: "fast-cluster"
bootstrap.memory_lock: true
network.bind_host: 0.0.0.0
network.publish_host: _ec2:privateIp_
transport.bind_host: 0.0.0.0
transport.publish_host: _ec2:privateIp_

discovery.seed_providers: ec2
discovery:
  ec2:
    host_type: private_ip
    tag.Environment: "production"
    tag.Cluster: "ecs-cluster"
    endpoint: ec2.eu-west-2.amazonaws.com
    availability_zones: eu-west-2a, eu-west-2b, eu-west-2c

cloud.node.auto_attributes: true
cluster.routing.allocation.awareness.attributes: aws_availability_zone
#xpack.security.enabled: false
#xpack.monitoring.enabled: true
#xpack.ml.enabled: false
#xpack.graph.enabled: false
#xpack.watcher.enabled: false
